### ISSUE TITLE
Question about input bed file needed for workflow

### ISSUE THREAD

**Issue by pshkrh** [mhorlacher/Benchmark-RBP#2]
Hello, first off I'd like to say thanks for all the work you put in for comparing and benchmarking these models!

I am trying to generate the input training and test data for the multi resbind model. I can see that there are multiple snakefiles which are required to be run in order for the final .fasta file to get generated. I am trying to do this for the ENCODE dataset, and I can see that the first step is already done and the peaks.bed files are present, so I moved onto the next step which is to run the workflow under the data/proc/ directory. 

However, I wasn't able to see any references to this file which seems to be needed as input for the workflow: bed = 'meta/gencode/processed/{GENCODE}/{GENOME}/gencode.{GENCODE}.{GENOME}.basic.annotation.transcripts.bed'

Could you please let me know the best way to obtain the file, and also the proper way of putting in the required files in the meta folder?

I'd also appreciate any information on a possibly simpler method to generate the training data for just a single model, instead of running the entire workflow.

I'm new to the field, and I'm not familiar with snakemake or snakefiles, so please correct me if my understanding isn't fully correct.

Thanks again!

**Comment by mhorlacher** [comment]
Dear @pshkrh, the _transcripts_ BED file needs to be obtained directly from https://www.gencodegenes.org and placed in the specified directory structure with {GENCODE}version (e.g. v42) and {GENOME} version (e.g. GRCh38). For ease of use, I've uploaded the processed samples, which you can access here: https://zenodo.org/records/10600977

We are planning to upload the full processed inputs eventually, however they are >100GB in size, so for now users need to process inputs manually using the specified samples. 

Best,
Marc
